background = 0xFF222222
base = 0xFF000000

# accent = 0xFF9F78FF
accent = 0xFF000000



text = 0xFFFFFFFF
bright_text = 0xFFFFFFFF

font_family = Lincoln/MITRE L/M 5x7
font_size = 16


rounding_large = 2
rounding_small = 2
